name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Run tests with coverage
        run: uv run --frozen pytest --cov=. --cov-report=term-missing

      - name: Run static analysis
        run: |
          uv run ruff .
          uv run black --check .
          uv run mypy .
